FROM python:3.12-slim

# Evita buffering (logs aparecem logo)
ENV PYTHONUNBUFFERED=1

# Pasta de trabalho dentro do container
WORKDIR /app

# Copia e instala dependências primeiro (melhor para cache)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o resto do código
COPY . .

# Por padrão, executa a app (podes passar argumentos no docker run)
CMD ["python", "file_manager.py"]